In [1]:
import pandas as pd

In [3]:
sales = pd.read_csv('/Users/alexgarcia/Desktop/CityUniversity/MSDS/DS522 Data Aquisition and Analytics/Modules/Module5/HOS05/sales_data_sample.csv', encoding= 'latin')
sales

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [4]:
sales.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='str')

In [5]:
data = pd.DataFrame(sales.loc[:50, ['ORDERNUMBER', 'CUSTOMERNAME', 'ADDRESSLINE1', 'POSTALCODE', 'STATUS']])
data.to_csv('new_sales.csv')

In [9]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [10]:
sales = pd.read_excel('/Users/alexgarcia/Desktop/CityUniversity/MSDS/DS522 Data Aquisition and Analytics/Modules/Module5/HOS05/sales.xlsx', sheet_name='Sheet1')
sales

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2003-02-24,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,2003-05-07,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,2003-07-01,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,2004-12-02,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,2005-01-31,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,2005-03-01,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,2005-03-28,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,2005-05-06,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [12]:
products = sales[['PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'PRICEEACH']]
products

      PRODUCTLINE  MSRP PRODUCTCODE  PRICEEACH
0     Motorcycles    95    S10_1678      95.70
1     Motorcycles    95    S10_1678      81.35
2     Motorcycles    95    S10_1678      94.74
3     Motorcycles    95    S10_1678      83.26
4     Motorcycles    95    S10_1678     100.00
...           ...   ...         ...        ...
2818        Ships    54    S72_3212     100.00
2819        Ships    54    S72_3212     100.00
2820        Ships    54    S72_3212     100.00
2821        Ships    54    S72_3212      62.24
2822        Ships    54    S72_3212      65.52

[2823 rows x 4 columns]

In [13]:
# Save the DataFrame to an Excel file
products.to_excel('products.xlsx', index=False, sheet_name='Products')

In [11]:
users = pd.read_json('/Users/alexgarcia/Desktop/CityUniversity/MSDS/DS522 Data Aquisition and Analytics/Modules/Module5/HOS05/users.json')
users

   id first_name  last_name                   email  gender      ip_address
0   1   Jeanette  Penddreth  jpenddreth0@census.gov  Female     26.58.193.2
1   2    Giavani   Frediani   gfrediani1@senate.gov    Male   229.179.4.212
2   3      Noell        Bea     nbea2@imageshack.us  Female  180.66.162.255
3   4    Willard      Valek          wvalek3@vk.com    Male    67.76.188.26

In [14]:
new_users = [{
    "id": 5,
    "first_name": "Christine",
    "last_name": "Molly",
    "email": "cm123@gmail.com",
    "gender": "Female",
    "ip_address": "126.58.193.2"
}, {
    "id": 6,
    "first_name": "Anne",
    "last_name": "Lee",
    "email": "al456@email.com",
    "gender": "Female",
    "ip_address": "129.279.40.212"}, {
    "id": 6,
    "first_name": "Anne",
    "last_name": "Lee",
    "email": "al456@email.com",
    "gender": "Female",
    "ip_address": "100.689.1.200"}]

new_df = pd.DataFrame(new_users)
new_df

   id first_name last_name            email  gender      ip_address
0   5  Christine     Molly  cm123@gmail.com  Female    126.58.193.2
1   6       Anne       Lee  al456@email.com  Female  129.279.40.212
2   6       Anne       Lee  al456@email.com  Female   100.689.1.200

In [15]:
df = pd.concat([users, new_df], ignore_index=True)
df

   id first_name  last_name                   email  gender      ip_address
0   1   Jeanette  Penddreth  jpenddreth0@census.gov  Female     26.58.193.2
1   2    Giavani   Frediani   gfrediani1@senate.gov    Male   229.179.4.212
2   3      Noell        Bea     nbea2@imageshack.us  Female  180.66.162.255
3   4    Willard      Valek          wvalek3@vk.com    Male    67.76.188.26
4   5  Christine      Molly         cm123@gmail.com  Female    126.58.193.2
5   6       Anne        Lee         al456@email.com  Female  129.279.40.212
6   6       Anne        Lee         al456@email.com  Female   100.689.1.200

In [16]:
df.to_json('new_users.json', orient='records')

In [17]:
pip install lxml

Collecting lxml
  Downloading lxml-6.1.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (4.0 kB)
Downloading lxml-6.1.0-cp311-cp311-macosx_10_9_x86_64.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 1.7 MB/s eta 0:00:00a 0:00:01
Installing collected packages: lxml
Successfully installed lxml-6.1.0

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [18]:
# read all HTML tables from specific URL
banks = pd.read_html("/Users/alexgarcia/Desktop/CityUniversity/MSDS/DS522 Data Aquisition and Analytics/Modules/Module5/HOS05/fdic_failed_bank_list.html")
# print the content
banks = banks[0]
banks

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"
...,...,...,...,...,...,...,...
542,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB","July 27, 2001","August 19, 2014"
543,Malta National Bank,Malta,OH,6629,North Valley Bank,"May 3, 2001","November 18, 2002"
544,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,"February 2, 2001","February 18, 2003"
545,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,"December 14, 2000","March 17, 2005"
546,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,"October 13, 2000","March 17, 2005"

In [19]:
# Add a new column to the df
banks['Close Date'] = pd.to_datetime(banks["Closing Date"])
banks

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date,Close Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016",2016-09-23
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016",2016-08-19
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016",2016-05-06
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016",2016-04-29
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016",2016-03-11
...,...,...,...,...,...,...,...,...
542,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB","July 27, 2001","August 19, 2014",2001-07-27
543,Malta National Bank,Malta,OH,6629,North Valley Bank,"May 3, 2001","November 18, 2002",2001-05-03
544,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,"February 2, 2001","February 18, 2003",2001-02-02
545,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,"December 14, 2000","March 17, 2005",2000-12-14
546,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,"October 13, 2000","March 17, 2005",2000-10-13

In [20]:
# Count the number of banks that closed per year
banks['Close Date'].dt.year.value_counts()

Close Date
2010    157
2009    140
2011     92
2012     51
2008     25
2013     24
2014     18
2002     11
2015      8
2016      5
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, dtype: int64

In [21]:
# Save DataFrame to an HTML file
banks.to_html('banks.html', index=False)

In [22]:
import sqlite3

# Create a connection to the SQLite database (or create the database if it doesn't exist)
conn = sqlite3.connect('sales_data.db')

# Create a cursor object to interact with the database
cursor = conn.cursor()

# Create a sales table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS sales_table (
        id INTEGER PRIMARY KEY,
        Date TEXT,
        Store TEXT,
        Product TEXT,
        Quantity INTEGER,
        Price REAL
    )
''')

# Commit the changes
conn.commit()

# Close the connection
conn.close()

In [23]:
import sqlite3

# Sample data to insert into the table
sales_data = [
    ('2023-07-01', 'Store A', 'Product 1', 5, 10.0),
    ('2023-07-02', 'Store B', 'Product 2', 3, 15.0),
    ('2023-07-03', 'Store A', 'Product 1', 2, 10.0),
    ('2023-07-04', 'Store C', 'Product 3', 8, 20.0),
    ('2023-07-05', 'Store B', 'Product 2', 1, 15.0)
]

# Reconnect to the SQLite database
conn = sqlite3.connect('sales_data.db')

# Create a cursor object
cursor = conn.cursor()

# Insert data into the sales_table
cursor.executemany('''
    INSERT INTO sales_table (Date, Store, Product, Quantity, Price)
    VALUES (?, ?, ?, ?, ?)
''', sales_data)

# Commit the changes
conn.commit()

# Close the connection
conn.close()

In [24]:
import pandas as pd
import sqlite3

# Sample DataFrame to write to the database
data = {
    'Date': ['2023-07-06', '2023-07-07'],
    'Store': ['Store D', 'Store E'],
    'Product': ['Product 4', 'Product 5'],
    'Quantity': [4, 7],
    'Price': [25.0, 30.0]
}
df_new = pd.DataFrame(data)

# Reconnect to the SQLite database
conn = sqlite3.connect('sales_data.db')

# Write the DataFrame to the sales_table
df_new.to_sql('sales_table', conn, if_exists='append', index=False)

# Commit the changes (not necessary for `to_sql`, but is a good practice)
conn.commit()

# Close the connection
conn.close()

print("New data has been added to the database.")

New data has been added to the database.

In [25]:
import pandas as pd
import sqlite3

# Reconnect to the SQLite database
conn = sqlite3.connect('sales_data.db')

# Load data from the sales_table into a Pandas DataFrame
df = pd.read_sql_query('SELECT * FROM sales_table', conn)

# Display the first few rows
print(df.head())

# Close the connection
conn.close()

   id        Date    Store    Product  Quantity  Price
0   1  2023-07-01  Store A  Product 1         5   10.0
1   2  2023-07-02  Store B  Product 2         3   15.0
2   3  2023-07-03  Store A  Product 1         2   10.0
3   4  2023-07-04  Store C  Product 3         8   20.0
4   5  2023-07-05  Store B  Product 2         1   15.0

In [26]:
import pandas as pd
import sqlite3

# Reconnect to the SQLite database
conn = sqlite3.connect('sales_data.db')

# Query the data
df = pd.read_sql_query('SELECT * FROM sales_table', conn)

# Display all the data
print(df)

# Close the connection
conn.close()

   id        Date    Store    Product  Quantity  Price
0   1  2023-07-01  Store A  Product 1         5   10.0
1   2  2023-07-02  Store B  Product 2         3   15.0
2   3  2023-07-03  Store A  Product 1         2   10.0
3   4  2023-07-04  Store C  Product 3         8   20.0
4   5  2023-07-05  Store B  Product 2         1   15.0
5   6  2023-07-06  Store D  Product 4         4   25.0
6   7  2023-07-07  Store E  Product 5         7   30.0