In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [3]:
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [5]:
df.sum(numeric_only=True)

total_bill    4827.77
tip            731.58
size           627.00
dtype: float64

In [6]:
df.mean(numeric_only=True)

total_bill    19.785943
tip            2.998279
size           2.569672
dtype: float64

In [7]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [8]:
df.groupby('time').mean(numeric_only=True)

        total_bill       tip      size
time
Lunch    17.168676  2.728088  2.411765
Dinner   20.797159  3.102670  2.630682

In [9]:
df.groupby('time').sum(numeric_only=True)

        total_bill     tip  size
time
Lunch      1167.47  185.51   164
Dinner     3660.30  546.07   463

In [10]:
df.groupby('time')['size'].sum()

time
Lunch     164
Dinner    463
Name: size, dtype: int64

In [11]:
for (time, group) in df.groupby('time'):
    print(f'{time}:\n{group}')

Lunch:
     total_bill   tip     sex smoker   day   time  size
77        27.20  4.00    Male     No  Thur  Lunch     4
78        22.76  3.00    Male     No  Thur  Lunch     2
79        17.29  2.71    Male     No  Thur  Lunch     2
80        19.44  3.00    Male    Yes  Thur  Lunch     2
81        16.66  3.40    Male     No  Thur  Lunch     2
..          ...   ...     ...    ...   ...    ...   ...
222        8.58  1.92    Male    Yes   Fri  Lunch     1
223       15.98  3.00  Female     No   Fri  Lunch     3
224       13.42  1.58    Male    Yes   Fri  Lunch     2
225       16.27  2.50  Female    Yes   Fri  Lunch     2
226       10.09  2.00  Female    Yes   Fri  Lunch     2

[68 rows x 7 columns]
Dinner:
     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

In [19]:
for (time, sex) in df.groupby(['time', 'sex']):
    print(f'{time}:\n{group}')

('Lunch', 'Male'):
     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]
('Lunch', 'Female'):
     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]
('Dinner', 'Male'):
     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]
('Dinner', 'Female'):
     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

In [20]:
df.groupby('time')['tip'].describe()

        count      mean       std   min  25%   50%     75%   max
time
Lunch    68.0  2.728088  1.205345  1.25  2.0  2.25  3.2875   6.7
Dinner  176.0  3.102670  1.436243  1.00  2.0  3.00  3.6875  10.0

In [21]:
# Create a new column that computes the tip percentage
df["tip_pct"] = df["tip"] / df["total_bill"]
# Create a groupby object using multiple keys, then retrieve the mean of the 'tip_pct'
df.groupby(["day", "smoker"])['tip_pct'].agg('mean')

day   smoker
Thur  Yes       0.163863
      No        0.160298
Fri   Yes       0.174783
      No        0.151650
Sat   Yes       0.147906
      No        0.158048
Sun   Yes       0.187250
      No        0.160113
Name: tip_pct, dtype: float64

In [23]:
# Create a groupby object using multiple keys, then retrieve the mean, min, max, & std of the 'tip_pct'
df.groupby(["day", "smoker"])['tip_pct'].agg(['mean', 'min', 'max', 'std'])

                 mean       min       max       std
day  smoker
Thur Yes     0.163863  0.090014  0.241255  0.039389
     No      0.160298  0.072961  0.266312  0.038774
Fri  Yes     0.174783  0.103555  0.263480  0.051293
     No      0.151650  0.120385  0.187735  0.028123
Sat  Yes     0.147906  0.035638  0.325733  0.061375
     No      0.158048  0.056797  0.291990  0.039767
Sun  Yes     0.187250  0.065660  0.710345  0.154134
     No      0.160113  0.059447  0.252672  0.042347

In [24]:
df.groupby(["day", "smoker"])['tip_pct'].agg([('average', 'mean'),('minimum', 'min'),('maximum', 'max'),('std dev', 'std')])

              average   minimum   maximum   std dev
day  smoker
Thur Yes     0.163863  0.090014  0.241255  0.039389
     No      0.160298  0.072961  0.266312  0.038774
Fri  Yes     0.174783  0.103555  0.263480  0.051293
     No      0.151650  0.120385  0.187735  0.028123
Sat  Yes     0.147906  0.035638  0.325733  0.061375
     No      0.158048  0.056797  0.291990  0.039767
Sun  Yes     0.187250  0.065660  0.710345  0.154134
     No      0.160113  0.059447  0.252672  0.042347

In [29]:
# Group by time, then compute the tip's max value and the size's min value
df.groupby('time').agg({'tip': max, 'size': min})

         tip  size
time
Lunch    6.7     1
Dinner  10.0     1

In [30]:
df.groupby('time')[['tip', 'size']].apply(lambda x: x[['tip', 'size']].sum(axis=1))

time
Lunch   77     8.00
        78     5.00
        79     4.71
        80     5.00
        81     5.40
               ...
Dinner  239    8.92
        240    4.00
        241    4.00
        242    3.75
        243    5.00
Length: 244, dtype: float64

In [31]:
new_row = pd.DataFrame({'total_bill': None, 'tip': None,
                        'sex': ['Female'], 'smoker': ['Yes'],
                        'day': ['Friday'], 'time': ['Dinner'],
                        'size': None, 'tip_pct': None})
df = pd.concat([df, new_row])
df

     total_bill   tip     sex smoker     day    time  size   tip_pct
0         16.99  1.01  Female     No     Sun  Dinner     2  0.059447
1         10.34  1.66    Male     No     Sun  Dinner     3  0.160542
2         21.01  3.50    Male     No     Sun  Dinner     3  0.166587
3         23.68  3.31    Male     No     Sun  Dinner     2  0.139780
4         24.59  3.61  Female     No     Sun  Dinner     4  0.146808
..          ...   ...     ...    ...     ...     ...   ...       ...
240       27.18  2.00  Female    Yes     Sat  Dinner     2  0.073584
241       22.67  2.00    Male    Yes     Sat  Dinner     2  0.088222
242       17.82  1.75    Male     No     Sat  Dinner     2  0.098204
243       18.78  3.00  Female     No    Thur  Dinner     2  0.159744
0           NaN   NaN  Female    Yes  Friday  Dinner  None       NaN

[245 rows x 8 columns]

In [32]:
def fill_mean(group):
    # Apply fillna with mean only to numeric columns
    numeric_cols = group.select_dtypes(include='number')
    return group.fillna(numeric_cols.mean())

df.groupby('time').apply(fill_mean)

            total_bill   tip     sex smoker  day    time size   tip_pct
time
Dinner 0         16.99  1.01  Female     No  Sun  Dinner    2  0.059447
       1         10.34  1.66    Male     No  Sun  Dinner    3  0.160542
       2         21.01  3.50    Male     No  Sun  Dinner    3  0.166587
       3         23.68  3.31    Male     No  Sun  Dinner    2  0.139780
       4         24.59  3.61  Female     No  Sun  Dinner    4  0.146808
...                ...   ...     ...    ...  ...     ...  ...       ...
Lunch  222        8.58  1.92    Male    Yes  Fri   Lunch    1  0.223776
       223       15.98  3.00  Female     No  Fri   Lunch    3  0.187735
       224       13.42  1.58    Male    Yes  Fri   Lunch    2  0.117735
       225       16.27  2.50  Female    Yes  Fri   Lunch    2  0.153657
       226       10.09  2.00  Female    Yes  Fri   Lunch    2  0.198216

[245 rows x 8 columns]

In [33]:
df.dropna(inplace=True)
df.groupby('time')[['total_bill', 'tip', 'size', 'tip_pct']].transform(lambda x: x + x.std())

     total_bill       tip      size   tip_pct
0     26.132029  2.446243  2.910241  0.126924
1     19.482029  3.096243  3.910241  0.228019
2     30.152029  4.936243  3.910241  0.234064
3     32.822029  4.746243  2.910241  0.207258
4     33.732029  5.046243  4.910241  0.214285
..          ...       ...       ...       ...
239   38.172029  7.356243  3.910241  0.271404
240   36.322029  3.436243  2.910241  0.141061
241   31.812029  3.436243  2.910241  0.155699
242   26.962029  3.186243  2.910241  0.165681
243   27.922029  4.436243  2.910241  0.227222

[244 rows x 4 columns]

In [34]:
df.groupby('time').filter(lambda x: x['size'].std() > 1)

     total_bill   tip     sex smoker   day   time size   tip_pct
77        27.20  4.00    Male     No  Thur  Lunch    4  0.147059
78        22.76  3.00    Male     No  Thur  Lunch    2  0.131810
79        17.29  2.71    Male     No  Thur  Lunch    2  0.156738
80        19.44  3.00    Male    Yes  Thur  Lunch    2  0.154321
81        16.66  3.40    Male     No  Thur  Lunch    2  0.204082
..          ...   ...     ...    ...   ...    ...  ...       ...
222        8.58  1.92    Male    Yes   Fri  Lunch    1  0.223776
223       15.98  3.00  Female     No   Fri  Lunch    3  0.187735
224       13.42  1.58    Male    Yes   Fri  Lunch    2  0.117735
225       16.27  2.50  Female    Yes   Fri  Lunch    2  0.153657
226       10.09  2.00  Female    Yes   Fri  Lunch    2  0.198216

[68 rows x 8 columns]

In [35]:
pd.pivot_table(df, index='time', columns='sex', values='tip', aggfunc=sum, fill_value=0)

sex     Female    Male
time
Dinner  156.11  389.96
Lunch    90.40   95.11