In [2]:
import pandas as pd

# Load the CSV into a DataFrame
sales_df = pd.read_csv('/Users/alexgarcia/Desktop/CityUniversity/MSDS/DS522 Data Aquisition and Analytics/Modules/Module4/PE04/sales.csv')
sales_df

          Date    Store    Product  Quantity  Price
0   2023-07-01  Store A  Product 1         5   10.0
1   2023-07-02  Store B  Product 2         3   15.0
2   2023-07-03  Store A  Product 3         2   20.0
3   2023-07-04  Store C  Product 1         8   10.0
4   2023-07-05  Store B  Product 3         1   20.0
5   2023-07-06  Store C  Product 2         6   15.0
6   2023-07-07  Store A  Product 1         7   10.0
7   2023-07-08  Store C  Product 3         2   20.0
8   2023-07-09  Store B  Product 2         5   15.0
9   2023-07-10  Store A  Product 2         3   15.0
10  2023-07-11  Store C  Product 1         4   10.0
11  2023-07-12  Store B  Product 3         7   20.0
12  2023-07-13  Store A  Product 1         6   10.0
13  2023-07-14  Store C  Product 2         3   15.0
14  2023-07-15  Store B  Product 3         4   20.0

In [4]:
# Summary information
print("Summary Information:")
sales_df.info()

Summary Information:
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      15 non-null     str
 1   Store     15 non-null     str
 2   Product   15 non-null     str
 3   Quantity  15 non-null     int64
 4   Price     15 non-null     float64
dtypes: float64(1), int64(1), str(3)
memory usage: 732.0 bytes

In [5]:
# Summary statistics for numerical columns
print("Summary Statistics:")
sales_df.describe()

Summary Statistics:

        Quantity      Price
count  15.000000  15.000000
mean    4.400000  15.000000
std     2.097618   4.225771
min     1.000000  10.000000
25%     3.000000  10.000000
50%     4.000000  15.000000
75%     6.000000  20.000000
max     8.000000  20.000000

In [6]:
# Add Total Sales column (Quantity * Price)
sales_df['Total Sales'] = sales_df['Quantity'] * sales_df['Price']

# Convert Date column to datetime
sales_df['Date'] = pd.to_datetime(sales_df['Date'])

print("DataFrame with Total Sales column and datetime Date:")
sales_df

DataFrame with Total Sales column and datetime Date:

         Date    Store    Product  Quantity  Price  Total Sales
0  2023-07-01  Store A  Product 1         5   10.0         50.0
1  2023-07-02  Store B  Product 2         3   15.0         45.0
2  2023-07-03  Store A  Product 3         2   20.0         40.0
3  2023-07-04  Store C  Product 1         8   10.0         80.0
4  2023-07-05  Store B  Product 3         1   20.0         20.0
5  2023-07-06  Store C  Product 2         6   15.0         90.0
6  2023-07-07  Store A  Product 1         7   10.0         70.0
7  2023-07-08  Store C  Product 3         2   20.0         40.0
8  2023-07-09  Store B  Product 2         5   15.0         75.0
9  2023-07-10  Store A  Product 2         3   15.0         45.0
10 2023-07-11  Store C  Product 1         4   10.0         40.0
11 2023-07-12  Store B  Product 3         7   20.0        140.0
12 2023-07-13  Store A  Product 1         6   10.0         60.0
13 2023-07-14  Store C  Product 2         3   15.0         45.0
14 2023-07-15  Store B  Product 3         4   20.0         80.0

In [7]:
# Filter sales that occurred in July
july_sales = sales_df[sales_df['Date'].dt.month == 7]
print("Sales in July:")
print(july_sales)

Sales in July:
         Date    Store    Product  Quantity  Price  Total Sales
0  2023-07-01  Store A  Product 1         5   10.0         50.0
1  2023-07-02  Store B  Product 2         3   15.0         45.0
2  2023-07-03  Store A  Product 3         2   20.0         40.0
3  2023-07-04  Store C  Product 1         8   10.0         80.0
4  2023-07-05  Store B  Product 3         1   20.0         20.0
5  2023-07-06  Store C  Product 2         6   15.0         90.0
6  2023-07-07  Store A  Product 1         7   10.0         70.0
7  2023-07-08  Store C  Product 3         2   20.0         40.0
8  2023-07-09  Store B  Product 2         5   15.0         75.0
9  2023-07-10  Store A  Product 2         3   15.0         45.0
10 2023-07-11  Store C  Product 1         4   10.0         40.0
11 2023-07-12  Store B  Product 3         7   20.0        140.0
12 2023-07-13  Store A  Product 1         6   10.0         60.0
13 2023-07-14  Store C  Product 2         3   15.0         45.0
14 2023-07-15  Store B  Product 3         4   20.0         80.0

In [8]:
# Filter sales where Quantity > 10
high_qty = sales_df[sales_df['Quantity'] > 10]
print("Sales where Quantity > 10:")
print(high_qty)

Sales where Quantity > 10:
Empty DataFrame
Columns: [Date, Store, Product, Quantity, Price, Total Sales]
Index: []

In [9]:
# Unique store names and total sales per store
print("Unique Stores:", sales_df['Store'].unique())
print("\nTotal Sales per Store:")
print(sales_df.groupby('Store')['Total Sales'].sum())

Unique Stores: <StringArray>
['Store A', 'Store B', 'Store C']
Length: 3, dtype: str

Total Sales per Store:
Store
Store A    265.0
Store B    360.0
Store C    295.0
Name: Total Sales, dtype: float64

In [10]:
# Unique products and average price per product
print("Unique Products:", sales_df['Product'].unique())
print("\nAverage Price per Product:")
print(sales_df.groupby('Product')['Price'].mean())

Unique Products: <StringArray>
['Product 1', 'Product 2', 'Product 3']
Length: 3, dtype: str

Average Price per Product:
Product
Product 1    10.0
Product 2    15.0
Product 3    20.0
Name: Price, dtype: float64

In [11]:
# Sort by Total Sales descending
sorted_df = sales_df.sort_values('Total Sales', ascending=False)
print("DataFrame sorted by Total Sales (descending):")
print(sorted_df)

DataFrame sorted by Total Sales (descending):
         Date    Store    Product  Quantity  Price  Total Sales
11 2023-07-12  Store B  Product 3         7   20.0        140.0
5  2023-07-06  Store C  Product 2         6   15.0         90.0
3  2023-07-04  Store C  Product 1         8   10.0         80.0
14 2023-07-15  Store B  Product 3         4   20.0         80.0
8  2023-07-09  Store B  Product 2         5   15.0         75.0
6  2023-07-07  Store A  Product 1         7   10.0         70.0
12 2023-07-13  Store A  Product 1         6   10.0         60.0
0  2023-07-01  Store A  Product 1         5   10.0         50.0
1  2023-07-02  Store B  Product 2         3   15.0         45.0
9  2023-07-10  Store A  Product 2         3   15.0         45.0
13 2023-07-14  Store C  Product 2         3   15.0         45.0
2  2023-07-03  Store A  Product 3         2   20.0         40.0
7  2023-07-08  Store C  Product 3         2   20.0         40.0
10 2023-07-11  Store C  Product 1         4   10.0         40.0
4  2023-07-05  Store B  Product 3         1   20.0         20.0

In [12]:
# Rank stores based on Total Sales
store_totals = sales_df.groupby('Store')['Total Sales'].sum()
store_totals_df = store_totals.reset_index()
store_totals_df['Rank'] = store_totals_df['Total Sales'].rank(ascending=False).astype(int)
store_totals_df = store_totals_df.sort_values('Rank')
print("Store Rankings by Total Sales:")
print(store_totals_df)

Store Rankings by Total Sales:
     Store  Total Sales  Rank
1  Store B        360.0     1
2  Store C        295.0     2
0  Store A        265.0     3

In [13]:
# Custom function: 10% discount if Quantity > 5
def discounted_price(row):
    if row['Quantity'] > 5:
        return row['Price'] * 0.90
    return row['Price']

# Apply the function to create Discounted Price column
sales_df['Discounted Price'] = sales_df.apply(discounted_price, axis=1)

print("DataFrame with Discounted Price column:")
sales_df

DataFrame with Discounted Price column:

,Date,Store,Product,Quantity,Price,Total Sales,Discounted Price
0,2023-07-01,Store A,Product 1,5,10.0,50.0,10.0
1,2023-07-02,Store B,Product 2,3,15.0,45.0,15.0
2,2023-07-03,Store A,Product 3,2,20.0,40.0,20.0
3,2023-07-04,Store C,Product 1,8,10.0,80.0,9.0
4,2023-07-05,Store B,Product 3,1,20.0,20.0,20.0
5,2023-07-06,Store C,Product 2,6,15.0,90.0,13.5
6,2023-07-07,Store A,Product 1,7,10.0,70.0,9.0
7,2023-07-08,Store C,Product 3,2,20.0,40.0,20.0
8,2023-07-09,Store B,Product 2,5,15.0,75.0,15.0
9,2023-07-10,Store A,Product 2,3,15.0,45.0,15.0
10,2023-07-11,Store C,Product 1,4,10.0,40.0,10.0
11,2023-07-12,Store B,Product 3,7,20.0,140.0,18.0
12,2023-07-13,Store A,Product 1,6,10.0,60.0,9.0
13,2023-07-14,Store C,Product 2,3,15.0,45.0,15.0
14,2023-07-15,Store B,Product 3,4,20.0,80.0,20.0