In [1]:
import pandas as pd
import numpy as np

In [3]:
data = [10, 20, 30, 40, 50]
series_with_index = pd.Series(data, index=['a', 'b', 'c', 'd', 'e'])

print("\nPandas Series with custom index:")
print(series_with_index)

Pandas Series with custom index:
a    10
b    20
c    30
d    40
e    50
dtype: int64

In [4]:
# Creating a Pandas DataFrame from a dictionary
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data_dict)

print("\nPandas DataFrame:")
print(df)

Pandas DataFrame:
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [7]:
# Creating a DataFrame from lists
names  = ['Alice', 'Bob', 'Charlie', 'David']
ages   = [25, 30, 35, 40]
cities = ['New York', 'Los Angeles', 'Chicago', 'Houston']

df_from_list = pd.DataFrame({'Name': names, 'Age': ages, 'City': cities})

print("\nDataFrame from lists:")
print(df_from_list)

DataFrame from lists:
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [8]:
df_from_list.set_index("Name", inplace=True)
df_from_list

         Age         City
Name
Alice     25     New York
Bob       30  Los Angeles
Charlie   35      Chicago
David     40      Houston

In [9]:
# Create a copy of the original df_from_list
df = df_from_list.copy()

# Accessing a single column
ages = df['Age']
print("\nAccessing a single column:")
print(ages)

# Access data of index 'Alice'
print("\nAccessing a single row:")
df.loc['Alice']

Accessing a single column:
Name
Alice      25
Bob        30
Charlie    35
David      40
Name: Age, dtype: int64

Accessing a single row:

Age           25
City    New York
Name: Alice, dtype: object

In [10]:
# Change back to the default index and store the another df variable
df = df.reset_index()
print("\nAccessing multiple columns:")
# Accessing multiple columns
df[['Name', 'City']]

Accessing multiple columns:

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston

In [11]:
# Accessing rows by index
first_row = df.iloc[0]
print("\nAccessing the first row:")
print(first_row)

# Accessing a specific row and column
specific_value = df.iloc[1, 2]
print("\nAccessing a specific value (row 1, column 2):")
print(specific_value)

Accessing the first row:
Name       Alice
Age           25
City    New York
Name: 0, dtype: object

Accessing a specific value (row 1, column 2):
Los Angeles

In [12]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [13]:
print("\nAccessing a specific value (all rows, column 2):")
df.iloc[:, 2]

Accessing a specific value (all rows, column 2):

0       New York
1    Los Angeles
2        Chicago
3        Houston
Name: City, dtype: str

In [14]:
# Column 0 (Name) at row index 2
print(df.iloc[2, 0])

Charlie

In [15]:
# Column 1 (Name) at row index 2
print(df.iloc[2, 1])

35

In [16]:
# Column 2 (Name) at row index 2
print(df.iloc[2, 2])

Chicago

In [17]:
# Filtering data based on conditions
age_filter = df[df['Age'] > 30]
print("\nFiltering data where age > 30:")
print(age_filter)

Filtering data where age > 30:
      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston

In [18]:
# Filtering data based on conditions
city_filter = df[df['City'] == 'Chicago']
print("\nFiltering data where city is Chicago:")
print(city_filter)

Filtering data where city is Chicago:
      Name  Age     City
2  Charlie   35  Chicago

In [19]:
# Adding a new column to the DataFrame
df['Salary'] = [50000, 60000, 70000, 80000]
print("\nDataFrame after adding a new column:")
df

DataFrame after adding a new column:

      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

In [20]:
# Modifying an existing column
df['New_Age'] = df['Age'] + 1
print("\nDataFrame after modifying the 'Age' column:")
df

DataFrame after modifying the 'Age' column:

      Name  Age         City  Salary  New_Age
0    Alice   25     New York   50000       26
1      Bob   30  Los Angeles   60000       31
2  Charlie   35      Chicago   70000       36
3    David   40      Houston   80000       41

In [21]:
# Dropping a column from the DataFrame
df_dropped = df.drop('New_Age', axis=1)
print("\nDataFrame after dropping the 'New_Age' column:")
df_dropped

DataFrame after dropping the 'New_Age' column:

      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      str
 1   Age      4 non-null      int64
 2   City     4 non-null      str
 3   Salary   4 non-null      int64
 4   New_Age  4 non-null      int64
dtypes: int64(3), str(2)
memory usage: 292.0 bytes

In [24]:
df.columns

Index(['Name', 'Age', 'City', 'Salary', 'New_Age'], dtype='str')

In [25]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [26]:
summary = df.describe()
print("\nDescriptive Statistics: ")
print(summary)

Descriptive Statistics:
             Age        Salary    New_Age
count   4.000000      4.000000   4.000000
mean   32.500000  65000.000000  33.500000
std     6.454972  12909.944487   6.454972
min    25.000000  50000.000000  26.000000
25%    28.750000  57500.000000  29.750000
50%    32.500000  65000.000000  33.500000
75%    36.250000  72500.000000  37.250000
max    40.000000  80000.000000  41.000000

In [27]:
# Creating a DataFrame
companies = {
    'Value': [220, 160, 140, 117, 94],
    'Change': [17.5, 11.9, -8.5, -2.1, 3.5],
    'Sector': ['Retail', 'Tech', 'Tech', 'Tech', 'Tech']
}

df = pd.DataFrame(companies, index=['Amazon', 'Google', 'Apple', 'Microsoft', 'Samsung'])
df

           Value  Change  Sector
Amazon       220    17.5  Retail
Google       160    11.9    Tech
Apple        140    -8.5    Tech
Microsoft    117    -2.1    Tech
Samsung       94     3.5    Tech

In [28]:
# Adding a scalar to all elements
print("\nDataFrame after adding 10 to all elements of the Value column:")
print(df['Value'].add(10))

# Subtracting a scalar from all elements
print("\nDataFrame after subtracting 5 from all elements of the Value column:")
print(df['Value'].sub(5))

# Multiplying all elements by a scalar
print("\nDataFrame after multiplying all elements of the Value column by 2:")
print(df['Value'].mul(2))

# divide and mod values in 'Value' by 2
div, rem = divmod(df['Value'], 2)
print("\nDataFrame after dividing all elements by 5:")
div, rem
# div is the floor of each values divided by 2
# rem is the remainder of each value divided by 2

DataFrame after adding 10 to all elements of the Value column:
Amazon       230
Google       170
Apple        150
Microsoft    127
Samsung      104
Name: Value, dtype: int64

DataFrame after subtracting 5 from all elements of the Value column:
Amazon       215
Google       155
Apple        135
Microsoft    112
Samsung       89
Name: Value, dtype: int64

DataFrame after multiplying all elements of the Value column by 2:
Amazon       440
Google       320
Apple        280
Microsoft    234
Samsung      188
Name: Value, dtype: int64

DataFrame after dividing all elements by 5:

(Amazon       110
 Google        80
 Apple         70
 Microsoft     58
 Samsung       47
 Name: Value, dtype: int64,
 Amazon       0
 Google       0
 Apple        0
 Microsoft    1
 Samsung      0
 Name: Value, dtype: int64)

In [29]:
# Sum of all elements in the DataFrame
total_sum = df.sum()
print("\nSum of all elements in each column:")
print(total_sum)

Sum of all elements in each column:
Value                        731
Change                      22.3
Sector    RetailTechTechTechTech
dtype: object

In [30]:
# Sum along the rows, pass numeric_only=True to avoid errors
row_sum = df.sum(axis=1, numeric_only=True)
print("\nSum of elements across each row:")
print(row_sum)

Sum of elements across each row:
Amazon       237.5
Google       171.9
Apple        131.5
Microsoft    114.9
Samsung       97.5
dtype: float64

In [31]:
# Mean of each column
mean_values = df.mean(numeric_only=True)
print("\nMean of each column:")
print(mean_values)

# Median of each column
median_values = df.median(numeric_only=True)
print("\nMedian of each column:")
print(median_values)

# Minimum values of each column
min_values = df.min(numeric_only=True)
print("\nMinimum value in each column:")
print(min_values)

# Maximum values of each column
max_values = df.max(numeric_only=True)
print("\nMaximum value in each column:")
print(max_values)

Mean of each column:
Value     146.20
Change      4.46
dtype: float64

Median of each column:
Value     140.0
Change      3.5
dtype: float64

Minimum value in each column:
Value     94.0
Change    -8.5
dtype: float64

Maximum value in each column:
Value     220.0
Change     17.5
dtype: float64

In [32]:
# Standard deviation of each column
std_values = df.std(numeric_only=True)
print("\nStandard deviation of each column:")
print(std_values)

# Variance of each column
variance_values = df.var(numeric_only=True)
print("\nVariance of each column:")
print(variance_values)

# The 50% quantile
quant_values = df.quantile(0.5, numeric_only=True)
print("\nThe 50% Quantile of each column:")
print(quant_values)

Standard deviation of each column:
Value     48.095738
Change    10.456003
dtype: float64

Variance of each column:
Value     2313.200
Change     109.328
dtype: float64

The 50% Quantile of each column:
Value     140.0
Change      3.5
Name: 0.5, dtype: float64

In [33]:
# Cumulative sum of each column
cumsum_values = df[['Value', 'Change']].cumsum()
print("\nCumulative sum of each column:")
print(cumsum_values)

# Cumulative product of each column
cumprod_values = df[['Value', 'Change']].cumprod()
print("\nCumulative product of each column:")
print(cumprod_values)

Cumulative sum of each column:
           Value  Change
Amazon       220    17.5
Google       380    29.4
Apple        520    20.9
Microsoft    637    18.8
Samsung      731    22.3

Cumulative product of each column:
                 Value       Change
Amazon             220     17.50000
Google           35200    208.25000
Apple          4928000  -1770.12500
Microsoft    576576000   3717.26250
Samsung    54198144000  13010.41875

In [34]:
# Correlation between columns
correlation_matrix = df.corr(numeric_only=True)
print("\nCorrelation matrix:")
print(correlation_matrix)

# Covariance between columns
covariance_matrix = df.cov(numeric_only=True)
print("\nCovariance matrix:")
print(covariance_matrix)

Correlation matrix:
           Value    Change
Value   1.000000  0.689536
Change  0.689536  1.000000

Covariance matrix:
          Value   Change
Value   2313.20  346.760
Change   346.76  109.328

In [35]:
# Define a custom function
def double_values(x):
    return x * 2

# Apply the custom function to the DataFrame
df_custom = df.apply(double_values)
print("\nDataFrame after applying custom function (doubling values):")
print(df_custom)

DataFrame after applying custom function (doubling values):
           Value  Change        Sector
Amazon       440    35.0  RetailRetail
Google       320    23.8      TechTech
Apple        280   -17.0      TechTech
Microsoft    234    -4.2      TechTech
Samsung      188     7.0      TechTech

In [36]:
# Get unique sector
print("\nUnique sectors:")
df['Sector'].unique()

Unique sectors:

<StringArray>
['Retail', 'Tech']
Length: 2, dtype: str

In [37]:
counts = df['Sector'].value_counts()
print("Value counts for each unique sector")
print(counts)

Value counts for each unique sector
Sector
Tech      4
Retail    1
Name: count, dtype: int64